### ISSUE TITLE
Is it possible to ignore files / folders?

### ISSUE THREAD

**Issue by baseten** [dobbydog/sftp-sync-deploy#3]
We have a folder on the server which is controlled via CMS, so the contents of the folder won't be stored locally. If we add this to the exclusion list then it will be deleted on the server. We'd just like the tool to ignore it altogether. Is this possible?

**Comment by dobbydog** [comment]
I added `excludeMode` option in ver 0.6. You can set it to `'ignore'` to simply ignore excluded files.
```
deploy(config, {
  exclude: ['cms-controlled-dir'],
  excludeMode: 'ignore'
}
```
