### ISSUE TITLE
privateKey, passphrase, agent...

### ISSUE THREAD

**Issue by hirasso** [dobbydog/sftp-sync-deploy#4]
Hi there,

I just installed your script, would love to have my work automatically being deployed inside my npm workflow. It works just fine, and now I would like to get it going with SFTP. Can you point me to a ressource on how to do that? Sorry, I am a frontend dev and have no clue about where to search for this information...

Basically I think I need to understand what the options `privateKey`, `passphrase` and  `agent` are all about.

**Comment by dobbydog** [comment]
These settings are optional. Just omit these if you don't use key authentication on your server, or ssh agent on your machine.
