### ISSUE TITLE
Sync only newer files

### ISSUE THREAD

**Issue by hirasso** [dobbydog/sftp-sync-deploy#5]
Hi there, me again – would it be possible to sync only newer files?

**Comment by dobbydog** [comment]
It's impossible at the moment. may be added if there are a lot of requests...

**Comment by gorootde** [comment]
Would be extremely useful. Also the name implies that there is a sync going on, and not only deleting the remote files replacing them with new ones.

**Comment by dobbydog** [comment]
I released 0.7.0 with this feature, and made it default behavior. Also added `forceUpload` option to disable it.
